### ISSUE TITLE
[Security Concerns] Backdoors reported by Antivirus

### ISSUE THREAD

**Issue by SH3LLco** [scambier/obsidian-text-extractor#56]
![threat2](https://github.com/scambier/obsidian-text-extractor/assets/124538862/0f344c12-7ea1-4b1f-ad2c-709be12f3760)
![threat1](https://github.com/scambier/obsidian-text-extractor/assets/124538862/0334bcb6-b11a-47f1-9467-5492e63fdda7)
![threat5](https://github.com/scambier/obsidian-text-extractor/assets/124538862/e54f644f-52c8-4789-b491-f3e76d225e90)
![threat4](https://github.com/scambier/obsidian-text-extractor/assets/124538862/d33f46a6-993c-4856-a061-cb18c4a4f13d)
![threat3](https://github.com/scambier/obsidian-text-extractor/assets/124538862/0980f20b-5de9-4f79-a1e2-2e64fa01b6a8)

**Comment by scambier** [comment]
@SH3LLco could you just confirm this issue was a sort of false positive? Just for peace of mind, thank you :)

In the meantime, for future readers: the quarantined files in this issue are the .json files (i.e. structured text) containing the extracted values from images and PDFs. Given that SH3LLco seems to work in security, it's probable that they have files containing malicious code, which were extracted as raw text. The antivirus was then rightfully triggered because the .json contained the code in text form.

_Of course_, if there was any known severe security issue, I'd do my best to fix it asap, and work with the Obsidian team to remove the plugin from the store if necessary.
