### ISSUE TITLE
[Feature request] 

Is it possible to someday support mobile? I use the Text Generator plugin which uses this plugin. But because I travel a lot, I use my Android phone almost exclusively. Mobile seems a natural for this plugin because users are using their phones for more and more. 

### ISSUE THREAD

**Issue by dvansoye** [scambier/obsidian-text-extractor#62]
I didn't see mobile support listed so I thought I would add this issue and the plugin itself says it is not compatible with mobile. 

"Text Extraction does not work on mobile."

When I use Text Extractor via Text Generator, I get the following error when trying to extract the transcy from a YouTube video.

TG Error: [Youtube Transcript]

Error: Request

Failed. MalformedURLException no protocol: /api/timedtext?

v=Luk9134u0Pk&ei=fmy_ZubUI_yM6dsPu6G3qAk&caps =ar&opi=112496729&exp=xbt&xoaf=5&hl=it&ip=0.0.0. 0&ipbits=0&expire=1723846382&sparams=ip,ipbits,ex pire, v,ei, caps, opi, exp, xoaf&signature=DCA560DFC624 5959E476F6B3F2809DDA84B94D58.62F85B1892C3E 228C8916E1E962A4B3FE7836021&key=yt8&kind=asr &lang=en

Selected extract Youtube

**Comment by scambier** [comment]
The "text extractor tool" referenced in the plugin Text Generator is totally unrelated to this project. Text Extractor (this plugin) also cannot process videos.

I do not support mobiles because, well, it's a lot of work. The last time I checked, PDF extraction simply crashed, and OCR wasn't functioning correctly (though it should work). OCR is pretty resource-intensive, and the wide range of Android phones - without even thinking about iOS - opens the door to many issues. It's just easier to _not_ do it.
